import { formatInvoiceMoney, invoiceCategoryLabel, type InvoiceSnapshot, invoicePanelClass } from "@/lib/invoiceUi";
export function InvoiceDocument({ snapshot, status }: { snapshot: InvoiceSnapshot; status: string }) {
  return <article className={`${invoicePanelClass} invoice-document space-y-5`}>
    {snapshot.identity?.appointment && <p className="text-sm">{snapshot.identity.appointment.notaryName}{snapshot.identity.appointment.title ? `, ${snapshot.identity.appointment.title}` : ""} · {snapshot.identity.appointment.kind} · v{snapshot.identity.appointment.version}{snapshot.identity.appointment.workArea ? ` · ${snapshot.identity.appointment.workArea}` : ""}</p>}
    {status === "VOID" && <p className="border-4 border-red-700 p-3 text-center text-3xl font-black text-red-700">VOID · DIBATALKAN</p>}
    <header className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-bold">{snapshot.office.name}</h2><p className="whitespace-pre-line">{snapshot.office.address}</p><p>{snapshot.office.phone}</p></div><div><h3 className="text-xl font-bold">INVOICE</h3><p>{snapshot.number}</p><p>Terbit: {new Intl.DateTimeFormat("id-ID", { timeZone: "Asia/Jakarta", dateStyle: "medium" }).format(new Date(snapshot.issuedAt))}</p></div></header>
    <div><p className="text-sm text-slate-500">Ditagihkan kepada</p><p className="font-semibold">{snapshot.client.name}</p><p className="whitespace-pre-line">{snapshot.client.address}</p>{snapshot.pekerjaan && <p>Pekerjaan: {snapshot.pekerjaan.judul}</p>}</div>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Rincian tagihan saat diterbitkan</caption><thead><tr>{["Item", "Qty", "Harga satuan", "Jumlah"].map((s) => <th scope="col" className="p-2" key={s}>{s}</th>)}</tr></thead><tbody>{snapshot.items.map((i, index) => <tr key={index} className="border-t border-slate-200"><td className="p-2">{i.desc}<p className="text-xs text-slate-500">{invoiceCategoryLabel[i.category]}</p></td><td className="p-2">{i.qty}</td><td className="whitespace-nowrap p-2">{formatInvoiceMoney(i.unitPrice)}</td><td className="whitespace-nowrap p-2">{formatInvoiceMoney(i.lineTotal)}</td></tr>)}</tbody></table></div>
    <p className="text-right text-xl font-bold">Total {formatInvoiceMoney(snapshot.totalAmount)}</p><p>Jatuh tempo: {snapshot.dueDate ?? "Tidak ditetapkan"}</p>{snapshot.notes && <p className="whitespace-pre-line">{snapshot.notes}</p>}
  </article>;
}
